[package]
name = "anvil"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "anvil"
path = "src/main.rs"

[dependencies]
ropey = "1.6"
crossterm = "0.28"
anyhow = "1"
unicode-width = "0.2"
regex = "1"
dirs = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tree-sitter = "0.27.0"
tree-sitter-rust = "0.24.2"
tree-sitter-python = "0.25.0"
tree-sitter-javascript = "0.25.0"
tree-sitter-go = "0.25.0"
tree-sitter-c = "0.24.2"
tree-sitter-bash = "0.25.1"
tree-sitter-json = "0.24.8"
tree-sitter-toml-ng = "0.7.0"
tree-sitter-yaml = "0.7.2"
tree-sitter-lua = "0.5.0"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
strip = true
